### ISSUE TITLE
Installing this package with pip does not install the necessary ` list_usb_serial_ports.sh`

### ISSUE THREAD

**Issue by deragent** [SengerM/PyticularsTCT#1]
When using the install command, as presented in the `README.md`:

    pip3 install git+https://github.com/SengerM/PyticularsTCT

one file is not properly installed, the `PyticularsTCT/list_usb_serial_ports.sh`.

In my case, the package is installed in the local user folder:

    /home/[USER]/.local/lib/python3.9/site-packages/PyticularsTCT/

When looking at this folder, the mentioned `.sh` file is not present.

The leads to the situation, that the um stages are not detected at all.

A workaround is to manually copy the mentioned `.sh` file into this directory:

    /home/[USER]/.local/lib/python3.9/site-packages/PyticularsTCT/
    wget https://raw.githubusercontent.com/SengerM/PyticularsTCT/master/PyticularsTCT/list_usb_serial_ports.sh

Cheers,
Johannes

**Comment by SengerM** [comment]
Thanks for pointing this out. I think now it should work automatically, I will close the issue. Please reopen if this still fails.

**Comment by deragent** [comment]
Indeed, a quick test on my computer shows that the `.sh` file is not included.

**Comment by SengerM** [comment]
*It is NOT included*, or *it is NOW included*? I have just tested it in a computer that has never seen this package before and `list_usb_serial_ports.sh` is there. What is your OS and pip version?

**Comment by deragent** [comment]
**NOW**

The amount of times I made this typo error. Sorry for the confusion :)
